import { notFound } from "next/navigation";
import Link from "next/link";
import { findCatalogProduct } from "@/lib/catalog";
import { saveProductAction } from "../../actions";
import ProductImageUpload from "../ProductImageUpload";
import CategorySelector from "../CategorySelector";
import { listCatalogProducts } from "@/lib/catalog";

export const dynamic = "force-dynamic";
const blank = { slug: "", name: "", tagline: "", price: 0, compareAtPrice: 0, category: "personalized", personalization: "photo", shape: "mug", supplierSku: "", requiresAdvance: true, occasions: [], rating: 0, reviews: 0, description: [], highlights: [], faqs: [], accent: ["#5b2a5e", "#d4a947"] as [string, string], badge: "", imageUrl: "", imageUrls: [] as string[], active: true, sortOrder: 0 };

export default async function ProductEditor({ params }: { params: Promise<{ slug: string }> }) {
  const { slug } = await params;
  const product = slug === "new" ? blank : await findCatalogProduct(slug, true);
  if (!product) notFound();
  const categories = Array.from(new Set(["personalized", "wellness", ...(await listCatalogProducts(true)).map((item) => item.category)])).sort();
  const field = "field mt-1";
  return <div className="container-page max-w-4xl py-10"><Link href="/admin/products" className="text-sm font-semibold text-plum">← All products</Link><h1 className="mt-3 text-3xl">{slug === "new" ? "Add product" : `Edit ${product.name}`}</h1><p className="mt-1 text-sm text-ink">Changes publish to the shop immediately after saving.</p>
    <form action={saveProductAction} className="mt-7 space-y-6"><section className="grid gap-4 rounded-2xl border border-line bg-white p-5 sm:grid-cols-2"><Field label="Product name *"><input name="name" required defaultValue={product.name} className={field} /></Field><Field label="URL slug *"><input name="slug" required pattern="[a-z0-9-]+" defaultValue={product.slug} className={field} /></Field><Field label="Short tagline"><input name="tagline" defaultValue={product.tagline} className={field} /></Field><div className="sm:col-span-2"><Field label="Product gallery (maximum 5 photos)"><ProductImageUpload initialUrls={product.imageUrls?.length ? product.imageUrls : product.imageUrl ? [product.imageUrl] : []} /></Field></div><Field label="Selling price (₹) *"><input name="price" required type="number" min="0" defaultValue={product.price} className={field} /></Field><Field label="Compare-at price (₹)"><input name="compareAtPrice" type="number" min="0" defaultValue={product.compareAtPrice} className={field} /></Field><Field label="Category"><CategorySelector categories={categories} initialCategory={product.category} /></Field><Field label="Personalization"><select name="personalization" defaultValue={product.personalization} className={field}><option value="none">None</option><option value="text">Text</option><option value="photo">Photo</option><option value="both">Text + photo</option></select></Field><Field label="Preview shape"><select name="shape" defaultValue={product.shape} className={field}>{["pendant", "mug", "frame", "mat"].map(x => <option key={x}>{x}</option>)}</select></Field><Field label="Supplier SKU"><input name="supplierSku" defaultValue={product.supplierSku} className={field} /></Field><Field label="Badge"><input name="badge" defaultValue={product.badge} placeholder="e.g. Bestseller" className={field} /></Field><Field label="Display order"><input name="sortOrder" type="number" min="0" defaultValue={product.sortOrder ?? 0} className={field} /></Field><Field label="Accent colour 1"><input name="accentStart" defaultValue={product.accent[0]} className={field} /></Field><Field label="Accent colour 2"><input name="accentEnd" defaultValue={product.accent[1]} className={field} /></Field><Field label="Rating"><input name="rating" type="number" min="0" max="5" step="0.1" defaultValue={product.rating} className={field} /></Field><Field label="Review count"><input name="reviews" type="number" min="0" defaultValue={product.reviews} className={field} /></Field><label className="flex items-center gap-2 text-sm font-semibold"><input name="active" type="checkbox" defaultChecked={product.active} /> Show this product on the shop</label><label className="flex items-center gap-2 text-sm font-semibold"><input name="requiresAdvance" type="checkbox" defaultChecked={product.requiresAdvance} /> Require online advance</label></section>
      <TextArea label="Description (one paragraph per line)" name="description" value={product.description.join("\n")} /><TextArea label="Highlights (one bullet per line)" name="highlights" value={product.highlights.join("\n")} /><TextArea label="Occasions (one per line)" name="occasions" value={product.occasions.join("\n")} /><TextArea label="FAQs (one per line: Question | Answer)" name="faqs" value={product.faqs.map(f => `${f.q} | ${f.a}`).join("\n")} />
      <button className="btn-primary" type="submit">Save product</button></form></div>;
}
function Field({ label, children }: { label: string; children: React.ReactNode }) { return <label className="text-sm font-semibold text-charcoal">{label}{children}</label>; }
function TextArea({ label, name, value }: { label: string; name: string; value: string }) { return <label className="block rounded-2xl border border-line bg-white p-5 text-sm font-semibold text-charcoal">{label}<textarea name={name} defaultValue={value} rows={5} className="field mt-2 font-normal" /></label>; }
